default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  username:
  password:

development:
  <<: *default
  database: register_for_class_development

test:
  <<: *default
  database: register_for_class_test

production:
  <<: *default
  database: register_for_class_production
