default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  username:
  password:

development:
  <<: *default
  database: pivot_development

test:
  <<: *default
  database: pivot_test

production:
  <<: *default
  database: pivot_production
